project:
  type: book
  output-dir: docs
  
  
page-navigation: true

format: 
  html:
    theme: cosmo
    code-fold: true
    code-copy: true
    code-overflow: wrap
    css: "/styles.css"
    toc: false
    number-depth: 2
    
execute:
  message: false
  warning: false  
  

book:
  reader-mode: false
  title: "Simulated Infectious Disease Outbreak in California"
  author: "Group 8: Erin Curlee, Val Stacey, Ana Terzo"
  date: "11/11/2025"  
  sidebar:
    search: false

  chapters:
    - index.qmd
    - part: "Data Preparation"
      chapters: 
        - milestones/03_milestone/03a_project_setup.qmd
        - milestones/03_milestone/03b_aligning_columns.qmd
        
    - part: "Restructuring Variables"
      chapters: 
        - milestones/03_milestone/03c_age_groups.qmd
        - milestones/03_milestone/03d_infection_dates.qmd
        - milestones/03_milestone/03e_race_ethnicity.qmd
        - milestones/03_milestone/03f_population_counts.qmd
        
    - milestones/03_milestone/03g_creating_final_datasets.qmd
    - milestones/03_milestone/03h_final_data_dictionary.qmd  
    
    - part: "Descriptive Exploration"
      chapters: 
        - milestones/03_milestone/03i_descriptive_stats.qmd

website:
  site-url: https://evalstace.github.io/Group08_PHW251_R/