project:
  type: book
  output-dir: docs
  
website:
  site-url: https://evalstace.github.io/Group08_PHW251_R/
 
page-navigation: true

format: 
  html:
    theme: [cosmo, _css/book_main_styles.scss]
    code-fold: true
    code-copy: true
    code-overflow: wrap
    toc: false
    number-depth: 1
    link-external-newwindow: true
    
execute:
  message: false
  warning: false  
  

book:
  reader-mode: false
  title: "Simulated Infectious Disease Outbreak in California"
  author: "Group 8: Erin Curlee, Val Stacey, Ana Terzo"
  date: "11/11/2025"  
  sidebar:
    search: false
    style: docked
    background: secondary
    pinned: true

  chapters:
    - index.qmd
    - part: "Data Preparation"
      chapters: 
        - chapters/chapter3/03a_project_setup.qmd
        - chapters/chapter3/03b_aligning_columns.qmd
        - chapters/chapter3/03c_age_groups.qmd
        - chapters/chapter3/03d_infection_dates.qmd
        - chapters/chapter3/03e_race_ethnicity.qmd
        - chapters/chapter3/03f_population_counts.qmd
        - chapters/chapter3/03g_creating_final_datasets.qmd
        - chapters/chapter3/03h_final_data_dictionary.qmd
    
    - part: "Descriptive Exploration"
      chapters: 
        - chapters/chapter3/03i_descriptive_stats.qmd

    
    - part: "Visualizations"
      chapters: 
        - chapters/chapter4/04a_cases_by_week.qmd
        
  appendices:
    - chapters/apx_library_refs.qmd
    - chapters/apx_custom_functions.qmd