project:
  type: book
  output-dir: docs
  resources: [".nojekyll"]
  
website:
  site-url: https://evalstace.github.io/Group08_PHW251_R/
  repo-url: https://github.com/EvalstacE/Group08_PHW251_R

book:
  bread-crumbs: false
  reader-mode: true
  back-to-top-navigation: true
  title: "Simulated Infectious Disease Outbreak in California"
  author: "Group 8: Erin Curlee, Val Stacey, Ana Terzo"
  date: "11/11/2025"  
  chapters:
    - index.qmd
    - part: "Data Preparation"
      chapters: 
        - milestones/03_milestone/03a_aligning_columns.qmd
        - milestones/03_milestone/03b_restructuring_variables.qmd
        - milestones/03_milestone/03c_creating_final_datasets.qmd
        - milestones/03_milestone/03d_final_data_dictionary.qmd        
    - part: "Descriptive Exploration"
      chapters: 
        - milestones/03_milestone/03e_descriptive_stats.qmd

page-navigation: true

format: 
  html:
    theme: cosmo
    code-fold: show
    code-copy: true
    code-overflow: wrap
    css: "www/styles.css"
    
execute:
  message: false
  warning: false